<?php
class CC_Rating {
 public static function init(){}
 public static function get($city,$voter_key=''){global $wpdb;$t=CC_DB::table();$rows=$wpdb->get_results($wpdb->prepare("SELECT stars,COUNT(*) n FROM $t WHERE city_id=%d GROUP BY stars",$city));if(!is_array($rows))$rows=array();$dist=array_fill(1,7,0);foreach($rows as $r)$dist[(int)$r->stars]=(int)$r->n;$count=(int)get_post_meta($city,'cc_rating_count',true);$avg=(float)get_post_meta($city,'cc_rating_avg',true);$user_rating=0;$changeable_at=0;if($voter_key){$row=$wpdb->get_row($wpdb->prepare("SELECT stars,updated_at FROM $t WHERE city_id=%d AND voter_key=%s",$city,$voter_key));if($row){$user_rating=(int)$row->stars;$changeable_at=strtotime($row->updated_at)+DAY_IN_SECONDS;}}$rank=self::rank_of($city);return array('average'=>$avg,'count'=>$count,'distribution'=>array_values($dist),'user_rating'=>$user_rating,'locked'=>($user_rating>0&&time()<$changeable_at),'changeable_at'=>$changeable_at,'rank'=>$rank,'total'=>self::total_cities());}
 public static function ranked_ids(){$cached=get_site_transient('cc_ranking');if(is_array($cached))return $cached;global $wpdb;$t=CC_DB::table();$rows=$wpdb->get_results("SELECT p.ID FROM {$wpdb->posts} p INNER JOIN $t r ON r.city_id=p.ID WHERE p.post_type='city' AND p.post_status='publish' GROUP BY p.ID ORDER BY SUM(r.stars) DESC, COUNT(r.id) ASC LIMIT 1000");if(!is_array($rows))$rows=array();$out=array();foreach($rows as $r)$out[]=(int)$r->ID;set_site_transient('cc_ranking',$out,6*HOUR_IN_SECONDS);return $out;}
 public static function rank_of($city){$pos=array_search((int)$city,self::ranked_ids(),true);return $pos===false?0:$pos+1;}
 public static function total_cities(){$n=wp_count_posts('city');return isset($n->publish)?(int)$n->publish:0;}
 public static function province_of($id){$terms=get_the_terms($id,'province_tax');if($terms&&!is_wp_error($terms)&&isset($terms[0]))return function_exists('sa_normalize_place_name')?sa_normalize_place_name($terms[0]->name,'province',''):$terms[0]->name;return '';}
 public static function sibling_count($id){$terms=get_the_terms($id,'province_tax');if($terms&&!is_wp_error($terms)&&isset($terms[0]))return (int)$terms[0]->count;return 0;}
 public static function top($limit=7){$ids=array_slice(self::ranked_ids(),0,(int)$limit);$out=array();foreach($ids as $i=>$id){$out[]=array('id'=>$id,'rank'=>$i+1,'title'=>function_exists('sa_entity_display_name')?sa_entity_display_name($id,''):get_the_title($id),'url'=>get_permalink($id),'avg'=>(float)get_post_meta($id,'cc_rating_avg',true),'total'=>(int)get_post_meta($id,'cc_rating_sum',true),'count'=>(int)get_post_meta($id,'cc_rating_count',true),'province'=>self::province_of($id),'siblings'=>self::sibling_count($id));}return $out;}
}
