<?php
if (!defined('ABSPATH')) exit;
class CC_OTP {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'routes'));}
 public static function routes(){register_rest_route('cc/v1','/auth/request',array('methods'=>'POST','callback'=>array(__CLASS__,'request'),'permission_callback'=>'__return_true'));register_rest_route('cc/v1','/auth/verify',array('methods'=>'POST','callback'=>array(__CLASS__,'verify'),'permission_callback'=>'__return_true'));}
 private static function phone($v){$v=preg_replace('/[^0-9+]/','',(string)$v); if(strpos($v,'+98')===0)$v='0'.substr($v,3); if(strpos($v,'98')===0)$v='0'.substr($v,2); return preg_match('/^09[0-9]{9}$/',$v)?$v:'';}
 public static function request($r){$phone=self::phone($r->get_param('phone'));if(!$phone)return new WP_Error('invalid_phone','شماره موبایل معتبر نیست',array('status'=>400));$key='cc_otp_'.md5($phone);$rate='cc_otp_rate_'.md5($phone.'_'.($_SERVER['REMOTE_ADDR']??''));$n=(int)get_transient($rate);if($n>=3)return new WP_Error('rate_limited','تعداد درخواست کد بیش از حد مجاز است',array('status'=>429));$code=(string)wp_rand(10000,99999);set_transient($key,wp_hash_password($code),2*MINUTE_IN_SECONDS);set_transient($rate,$n+1,HOUR_IN_SECONDS);$sent=self::send($phone,$code);if(is_wp_error($sent))return $sent;return array('success'=>true,'message'=>'کد ورود ارسال شد.','expires_in'=>120);}
 private static function send($phone,$code){$url=trim(get_option('cc_sms_endpoint',''));if(!$url){if(defined('WP_DEBUG')&&WP_DEBUG)error_log('CC OTP '.$phone.': '.$code);return true;} $res=wp_remote_post($url,array('timeout'=>10,'headers'=>array('Content-Type'=>'application/json','X-API-Key'=>get_option('cc_sms_key','')),'body'=>wp_json_encode(array('to'=>$phone,'message'=>'کد ورود سرزمین آریان: '.$code,'sender'=>get_option('cc_sms_sender','')))));if(is_wp_error($res)||wp_remote_retrieve_response_code($res)>=400)return new WP_Error('sms_failed','ارسال پیامک انجام نشد',array('status'=>503));return true;}
 public static function verify($r){$phone=self::phone($r->get_param('phone'));$code=preg_replace('/[^0-9]/','',(string)$r->get_param('code'));$hash=get_transient('cc_otp_'.md5($phone));if(!$phone||strlen($code)!==5||!$hash||!wp_check_password($code,$hash))return new WP_Error('invalid_otp','کد ورود نادرست یا منقضی شده است',array('status'=>400));delete_transient('cc_otp_'.md5($phone));$login='cc_'.md5($phone);$user=get_user_by('login',$login);if(!$user){$id=wp_insert_user(array('user_login'=>$login,'user_pass'=>wp_generate_password(32,true,true),'display_name'=>'کاربر '.substr($phone,-4)));if(is_wp_error($id))return $id;$user=get_user_by('id',$id);update_user_meta($id,'cc_phone',$phone);}wp_set_auth_cookie($user->ID,true);return array('success'=>true,'message'=>'ورود با موفقیت انجام شد.','user_id'=>$user->ID);}
}
