<?php
if (!defined('ABSPATH')) exit;
class CC_Moderation {
 public static function init(){add_action('add_meta_boxes',array(__CLASS__,'box'));add_action('save_post_cc_submission',array(__CLASS__,'save'),10,2);add_filter('manage_cc_submission_posts_columns',array(__CLASS__,'columns'));add_action('manage_cc_submission_posts_custom_column',array(__CLASS__,'column'),10,2);}
 public static function columns($c){$c['cc_review']='بررسی';return $c;}
 public static function column($col,$id){if($col!=='cc_review')return;$who=(int)get_post_meta($id,'cc_reviewed_by',true);$date=get_post_meta($id,'cc_reviewed_at',true);echo $who?'بررسی‌شده در '.esc_html(wp_date('Y/m/d H:i',strtotime($date))):'در انتظار بررسی';}
 public static function box(){add_meta_box('cc_moderation','بررسی مشارکت',array(__CLASS__,'render'),'cc_submission','side','high');}
 public static function render($post){wp_nonce_field('cc_moderate','cc_moderate_nonce');$city=(int)get_post_meta($post->ID,'cc_city_id',true);$img=(int)get_post_meta($post->ID,'cc_image_id',true);echo '<p><strong>شهر:</strong> '.esc_html(get_the_title($city)).'</p><p><strong>نوع:</strong> '.esc_html(get_post_meta($post->ID,'cc_type',true)).'</p>';if($img)echo wp_get_attachment_image($img,'medium');echo '<p><label for="cc_review_note">یادداشت بررسی</label><textarea name="cc_review_note" id="cc_review_note" style="width:100%">'.esc_textarea(get_post_meta($post->ID,'cc_review_note',true)).'</textarea></p><p><button class="button button-primary" name="cc_action" value="approve">تأیید و انتشار</button> <button class="button" name="cc_action" value="needs_edit">درخواست اصلاح</button> <button class="button" name="cc_action" value="reject">رد مشارکت</button></p>';}
 public static function save($id,$post){if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!CC_Roles::can_review($id)||!isset($_POST['cc_moderate_nonce'])||!wp_verify_nonce($_POST['cc_moderate_nonce'],'cc_moderate'))return;if(isset($_POST['cc_review_note']))update_post_meta($id,'cc_review_note',sanitize_textarea_field($_POST['cc_review_note']));$action=sanitize_key($_POST['cc_action']??'');$map=array('approve'=>'publish','reject'=>'rejected','needs_edit'=>'needs_edit');if(isset($map[$action])){ $from=get_post_status($id); $to=$map[$action]; wp_update_post(array('ID'=>$id,'post_status'=>$to)); update_post_meta($id,'cc_reviewed_by',get_current_user_id()); update_post_meta($id,'cc_reviewed_at',current_time('mysql')); if($to==='publish'){ $type=get_post_meta($id,'cc_type',true); $points=array('place'=>20,'food'=>20,'correction'=>8,'report'=>5,'tip'=>3); CC_Gamification::award((int)$post->post_author,(int)($points[$type]??3),'تأیید مشارکت',$id); CC_Gamification::award_badges((int)$post->post_author); } global $wpdb; $wpdb->insert(CC_DB::logs(),array('submission_id'=>$id,'reviewer_id'=>get_current_user_id(),'from_status'=>$from,'to_status'=>$to,'note'=>sanitize_textarea_field($_POST['cc_review_note']??''),'created_at'=>current_time('mysql')),array('%d','%d','%s','%s','%s','%s'));}}
}
